/**
 * Generate docs/WALKTHROUGH.md by actually playing the game.
 *
 *   npx vite-node tools/build_walkthrough.mjs
 *
 * The route is read out of tests/walkthrough.test.ts rather than restated, so
 * the document and the test can never disagree: if the walkthrough stops
 * working, the test goes red and this file changes with it.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { roomById } from "../src/data/index";
import { Session } from "../src/session";
import { carriedCount, createWorld } from "../src/engine/world";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/* ---------------------------------------------------------------- the route -- */

const test = readFileSync(resolve(ROOT, "tests/walkthrough.test.ts"), "utf8");
const start = test.indexOf("const WINNING_PATH");
const block = test.slice(start, test.indexOf("\n];", start));

/** @type {{ note?: string, cmds: string[] }[]} */
const steps = [];
for (const raw of block.split("\n").slice(1)) {
  const line = raw.trim();
  if (line.startsWith("//")) {
    steps.push({ note: line.slice(2).trim(), cmds: [] });
  } else if (line) {
    const cmds = [...line.matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    if (steps.length === 0) steps.push({ cmds: [] });
    steps[steps.length - 1].cmds.push(...cmds);
  }
}

/* ------------------------------------------------------------------- play it -- */

const MOVE = /^(n|s|e|w|u|d|north|south|east|west|up|down)$/;

const session = new Session(createWorld(99));
session.begin();

const body = [];
let count = 0;

for (const step of steps) {
  if (step.note) body.push(`\n### ${step.note}\n`);

  for (const command of step.cmds) {
    const before = session.world.room;
    const result = session.send(command);
    count += 1;

    const room = roomById.get(session.world.room);
    const moved = session.world.room !== before;
    const reply = result.lines
      .filter(
        (l) => l.kind !== "room" && l.kind !== "exits" && l.kind !== "objects",
      )
      .map((l) => l.text)
      .join(" ")
      .trim();

    if (MOVE.test(command)) {
      body.push(`- \`${command}\` → **${room?.name}**`);
    } else {
      const arrow = moved ? ` → **${room?.name}**` : "";
      body.push(`- \`${command}\`${arrow}` + (reply ? `\n  > ${reply}` : ""));
    }
  }
}

if (session.world.ended?.outcome !== "win") {
  console.error(
    `the route did not win (ended: ${session.world.ended?.outcome ?? "never"})`,
  );
  process.exit(1);
}

/* --------------------------------------------------------------- the document -- */

const doc = `# The Red Door — walkthrough

Generated by playing the game: \`npx vite-node tools/build_walkthrough.mjs\`.
The route is read from \`tests/walkthrough.test.ts\`, which asserts it reaches
*HAPPY DREAMS*, so this document cannot drift from the code.

**${count} commands.** Carrying ${carriedCount(session.world)} at the end.

---

## Before you start

- **The carrying limit is six**, and it is the hardest constraint in the game.
  Both mummies want four items at once, so the route stashes things in room 1
  (next door to both of them) and at the western hub, and comes back for them.
- **The corridor west of room 1 stays shut** until you have looked into both
  alcoves — north *and* south.
- **Five ways to die**: grabbing a snake bare-handed, drinking the pool, swimming
  in the pool, climbing down into the snake-pit, and turning up to Thoth a third
  time with no gift.
- **One way to make the game unwinnable without dying**: eating the funeral FOOD.
  The male mummy needs it and there is only one. This remake warns you first; the
  original did not.
- \`undo\` takes back any move, including a death.

## The dependency that shapes the route

The JOKE comes from the *female* mummy, and you need it to kill the fly, which
buys the silver JUG from the spider, which holds the embalming fluid that the
*male* mummy wants. So the female mummy has to be satisfied first — which means
the Soothsayer, the Scarlet Room box, the Treasure Room and the Concubine all
come before anything on the male mummy's list.

---

## The route
${body.join("\n")}

---

## The garden maze

Rooms 24–28 all read *"You are in the exotic ornamental garden"*. The only thing
telling them apart is the ink colour, which this remake keeps as the accent.

| From | N | S | E | W |
|---|---|---|---|---|
| 24 | 24 | **13 — out** | 26 | 24 |
| 25 | 25 | 25 | **28** | 24 |
| 26 | 25 | **13 — out** | 27 | 24 |
| 27 | 25 | 27 | 27 | 26 |
| 28 | 28 | 27 | 28 | 28 |

In from the patio: \`n\` \`e\` \`n\` \`e\`. Out again: \`s\` \`w\` \`s\`.

## Things worth trying that are not on the route

- \`examine\` almost anything — most of the game's character is in the responses,
  and several are jokes at the player's expense.
- \`listen\` in the Soothsayer's room before and after giving him the runes.
- \`examine skeleton\` in the Treasure Room. Twice.
- \`say abracadabra\` in the BLACK room after reading the symbols. It is a red
  herring, and the game says so.
- \`tell joke\` to the cow, the Soothsayer, the Concubine and the mummy — each has
  its own answer.
- \`milk cow\`.
`;

writeFileSync(resolve(ROOT, "docs/WALKTHROUGH.md"), doc);
console.log(`docs/WALKTHROUGH.md — ${count} commands, ends in a win`);
