/**
 * Generate docs/WALKTHROUGH.md by actually playing the game.
 *
 *   npx vite-node tools/build_walkthrough.mjs
 *
 * The route is read out of tests/walkthrough.test.ts rather than restated, so
 * the document and the test can never disagree: if the walkthrough stops
 * working, the test goes red and this file changes with it.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { roomById } from "../src/data/index";
import { Session } from "../src/session";
import { carriedCount, createWorld } from "../src/engine/world";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/* ---------------------------------------------------------------- the route -- */

const test = readFileSync(resolve(ROOT, "tests/walkthrough.test.ts"), "utf8");
const start = test.indexOf("const WINNING_PATH");
const block = test.slice(start, test.indexOf("\n];", start));

/** @type {{ note?: string, cmds: string[] }[]} */
const steps = [];
for (const raw of block.split("\n").slice(1)) {
  const line = raw.trim();
  if (line.startsWith("//")) {
    steps.push({ note: line.slice(2).trim(), cmds: [] });
  } else if (line) {
    const cmds = [...line.matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    if (steps.length === 0) steps.push({ cmds: [] });
    steps[steps.length - 1].cmds.push(...cmds);
  }
}

/* ------------------------------------------------------------------- play it -- */

const MOVE = /^(n|s|e|w|u|d|north|south|east|west|up|down)$/;

const session = new Session(createWorld(99));
session.begin();

const body = [];
let count = 0;

for (const step of steps) {
  if (step.note) body.push(`\n### ${step.note}\n`);

  for (const command of step.cmds) {
    const before = session.world.room;
    const result = session.send(command);
    count += 1;

    const room = roomById.get(session.world.room);
    const moved = session.world.room !== before;
    const reply = result.lines
      .filter(
        (l) => l.kind !== "room" && l.kind !== "exits" && l.kind !== "objects",
      )
      .map((l) => l.text)
      .join(" ")
      .trim();

    if (MOVE.test(command)) {
      body.push(`- \`${command}\` → **${room?.name}**`);
    } else {
      const arrow = moved ? ` → **${room?.name}**` : "";
      body.push(`- \`${command}\`${arrow}` + (reply ? `\n  > ${reply}` : ""));
    }
  }
}

if (session.world.ended?.outcome !== "win") {
  console.error(
    `the route did not win (ended: ${session.world.ended?.outcome ?? "never"})`,
  );
  process.exit(1);
}

/* --------------------------------------------------------------- the document -- */

const doc = `# The Red Door — walkthrough

Generated by playing the game: \`npx vite-node tools/build_walkthrough.mjs\`.
The route is read from \`tests/walkthrough.test.ts\`, which asserts it reaches
*HAPPY DREAMS*, so this document cannot drift from the code.

**${count} commands.** Carrying ${carriedCount(session.world)} at the end.

---

## Before you start

- **The carrying limit is six**, and it is the hardest constraint in the game.
  Both mummies want four items at once, so the route stashes things in room 1
  (next door to both of them) and at the western hub, and comes back for them.
- **The corridor west of room 1 stays shut** until you have looked into both
  alcoves — north *and* south.
- **Five ways to die**: grabbing a snake bare-handed, drinking the pool, swimming
  in the pool, climbing down into the snake-pit, and turning up to Thoth a third
  time with no gift.
- **One way to make the game unwinnable without dying**: eating the funeral FOOD.
  The male mummy needs it and there is only one. This remake warns you first; the
  original did not.
- \`undo\` takes back any move, including a death.

## The dependency that shapes the route

The JOKE comes from the *female* mummy, and you need it to kill the fly, which
buys the silver JUG from the spider, which holds the embalming fluid that the
*male* mummy wants. So the female mummy has to be satisfied first — which means
the Soothsayer, the Scarlet Room box, the Treasure Room and the Concubine all
come before anything on the male mummy's list.

---

## The route
${body.join("\n")}

---

## The garden maze

Rooms 24–28 all read *"You are in the exotic ornamental garden"*. The only thing
telling them apart is the ink colour, which this remake keeps as the accent.

| From | N | S | E | W |
|---|---|---|---|---|
| 24 | 24 | **13 — out** | 26 | 24 |
| 25 | 25 | 25 | **28** | 24 |
| 26 | 25 | **13 — out** | 27 | 24 |
| 27 | 25 | 27 | 27 | 26 |
| 28 | 28 | 27 | 28 | 28 |

In from the patio: \`n\` \`e\` \`n\` \`e\`. Out again: \`s\` \`w\` \`s\`.

## EXAMINE is not decoration

Five things in this game do not exist until you look at something:

| Examine | in | and you get |
|---|---|---|
| the haystack | the byre | Cleopatra's NEEDLE |
| DOWN | the room full of DOWN | navel FLUFF |
| the FLUFF | anywhere | the RUBY |
| the empty glass case | the Treasure Room | the NECKLACE |
| the mulberry bush | garden room 28 | the silkworms' THREAD |

Several more responses are the *only* clue you get for a puzzle:

- **the Soothsayer** — "he could be of some assistance given some **sure n**ews"
  is the whole hint for the RUNES.
- **the catch**, inside the mummy case — "there's the **RUB**!" is how you learn
  to turn the token gold.
- **the pool** — says outright that it is embalming fluid, which is what the male
  mummy wants and what kills you if you drink it.
- **the SPHINX** — "perhaps it doesn't like that fly there" points at the JOKE.
- **the PIPE** — "a good BLOW in the right place may help".

So examine everything, in every room. It is the closest thing the game has to a
hint system, and roughly half the puzzle chain is hidden in it.

## Jokes, which do nothing at all

These change no state and unlock nothing. They are here because the authors were
enjoying themselves, and are worth a look once you have finished:

- EXAMINE SKELETON in the Treasure Room, then again — it sings, then it is too
  tired to sing.
- EXAMINE BAT in the alcove: it is a character from another Tartan Software
  adventure on the same compilation tape.
- EXAMINE SPIDER: he is called Ernie, and SAY ERNIE gets a reply.
- MILK COW. EXAMINE PIT. EXAMINE UP, in the room full of DOWN.
- SAY ABRACADABRA in the BLACK room. Examining the symbols there says they are
  "not necessarily the ABRACADABRA type", so saying it anyway is taking the bait
  — and the answer is three brush-offs in a row, which is the joke.
- TELL JOKE to the cow, the Soothsayer and the Concubine: each has its own reply,
  and none of them is amused.
`;

writeFileSync(resolve(ROOT, "docs/WALKTHROUGH.md"), doc);
console.log(`docs/WALKTHROUGH.md — ${count} commands, ends in a win`);
